### ISSUE TITLE
base images

### ISSUE THREAD

**Issue by martintrojer** [juxt/docker#2]
I don't see much value in clojure/java base images, or to be more precise I see them pushed to a docker registry pointless.

For docker 'deliverables' I end up only depending on the disto-base (ubuntu:trusty in my case) and then everything else in-line in one dockerfile.
- The base image never has everything you'll need, so you always have to derive from it in a new Dockerfile.
- I don't want a 'base' to dictate java / lein versions. And overriding the base versions is just wrong.
- If you upgrade a base (due to security updates for instance) you still have to re-build all your downstream containers. If you have to rebuild them anyway, what is the point of the base.
- These bases are useless for building devbox-containers

Finally a word on funky ditros (arch, alpine). Sure, size is an issue but what trumps everything in my mind is reliable security updates. Docker images (in prod) have to be constantly 'apt-get upgrade'-d since they don't auto-upgrade/auto-relaunch services like say a ubuntu server. I just don't trust the smaller distros to promote security updates through (to legacy versions) like debian does.

**Comment by hraberg** [comment]
I think these are all valid points, we're experimenting and learning as we go. I don't expect anyone is looking to dictate standard issue Juxt Dockerfiles here :-) . I also don't plan to push any of the Alpine stuff to the public repo anytime soon.

Everyone has commit access to this repo now I think, just add a directory exploring your path.

**Comment by hraberg** [comment]
Also, to clarify around "funky" distros. The images I added only had one single goal - which might not even matter - to see how far you can get the size down. They're simply built with the official Clojure image as blueprint, but based on Alpine.

**Comment by martintrojer** [comment]
The 'official clojure image', don't understand how that could ever be useful either :)

Anyway, no criticism of your stellar work, small images are definitely a very good thing (pulled a 5gb image the other day).

I guess I'm trying to figure out how to turn this repo into something useful for us an others.
